import type { Completions } from "effect/unstable/cli"

const nuString = (value: string): string => JSON.stringify(value)

const identifier = (name: string): string => /[\w-]+/u.exec(name)?.[0] ?? "argument"

const completerName = (path: readonly string[], argument: string): string =>
  ["nu-complete", ...path, argument].join(" ")

const flagLine = (flag: Completions.FlagDescriptor): string => {
  const alias = flag.aliases.find((candidate) => candidate.length === 1)
  const name = alias === undefined ? `--${flag.name}` : `--${flag.name}(-${alias})`
  const type = flag.type._tag === "Boolean" ? "" : ": string"
  const description = flag.description === undefined ? "" : ` # ${flag.description}`
  return `${name}${type}${description}`
}

const argumentLine = (
  argument: Completions.ArgumentDescriptor,
  path: readonly string[],
): string => {
  const name = identifier(argument.name)
  const spread = argument.variadic ? "..." : ""
  const optional = argument.required || argument.variadic ? "" : "?"
  const completer =
    argument.type._tag === "Choice" && argument.type.values.length > 0
      ? `@${nuString(completerName(path, name))}`
      : ""
  const description = argument.description === undefined ? "" : ` # ${argument.description}`
  return `${spread}${name}${optional}: string${completer}${description}`
}

const completerLines = (
  descriptor: Completions.CommandDescriptor,
  path: readonly string[],
): readonly string[] => {
  const lines: string[] = []
  for (const argument of descriptor.arguments) {
    if (argument.type._tag !== "Choice" || argument.type.values.length === 0) {
      continue
    }
    lines.push(
      `def ${nuString(completerName([...path, descriptor.name], identifier(argument.name)))} [] {`,
      "  [",
    )
    for (const value of argument.type.values) {
      lines.push(`    ${nuString(value)}`)
    }
    lines.push("  ]", "}", "")
  }
  return lines
}

const externLines = (
  executable: string,
  descriptor: Completions.CommandDescriptor,
  path: readonly string[],
): readonly string[] => {
  const current = [...path, descriptor.name]
  const target = path.length === 0 ? executable : nuString(current.join(" "))
  const signature = [
    ...descriptor.flags.map(flagLine),
    ...descriptor.arguments.map((argument) => argumentLine(argument, current)),
  ]
  if (signature.length === 0) {
    return [`export extern ${target} []`, ""]
  }
  return [`export extern ${target} [`, ...signature.map((line) => `  ${line}`), "]", ""]
}

const generateCommand = (
  executable: string,
  descriptor: Completions.CommandDescriptor,
  path: readonly string[],
): readonly string[] => {
  const lines = [...completerLines(descriptor, path), ...externLines(executable, descriptor, path)]
  const current = [...path, descriptor.name]
  for (const subcommand of descriptor.subcommands) {
    lines.push(...generateCommand(executable, subcommand, current))
  }
  return lines
}

const generateNushell = (executable: string, descriptor: Completions.CommandDescriptor): string => {
  const lines = [
    `# ${executable} shell completions for nushell`,
    `# Generated by ${executable} completions nushell; do not edit by hand.`,
    "",
    ...generateCommand(executable, descriptor, []),
  ]
  return `${lines.join("\n")}\n`
}

export { generateNushell }
